[package]
name = "indent_write"
version = "1.0.0"
authors = ["Nathan West <Lucretiel@gmail.com>"]
edition = "2018"

readme = "README.md"
license = "MPL-2.0"
description = "Simple Write adapters to add line indentation"
repository = "https://github.com/Lucretiel/indent-write"

[dependencies]
